# Build stage
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./        # Copy frontend package.json
RUN npm install
COPY ./src ./src             # Copy the frontend source code
COPY public ./public         # Copy public folder
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
